[package]
name = "ferrugem"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.39.1", features = ["full"] }
toml = "0.8.16"
tracing = "0.1"
tracing-subscriber = "0.3"
